server:
  port: 8081

spring:
  application:
    name: spring-boot-admin-client
  security:
    user:
      name: client
      password: client
  boot:
    admin:
      client:
        url: http://localhost:8080
        username: admin
        password: admin
        instance:
          management-base-url: http://localhost:8081
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: ${spring.application.name}.log
    max-history: 5
    max-size: 10MB
